# Generated by Django 3.2.12 on 2022-07-01 21:12

from django.db import migrations


def update_dates(apps, schema_editor):
    sales_invoice = apps.get_model('sales', 'Sales')
    ledger_payment = apps.get_model('customer', 'CustomerCredit')

    for i in sales_invoice.objects.all():
        i.dated = i.sale_date
        i.save()

    for p in ledger_payment.objects.all():
        p.dated = p.credit_date
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customercredit'),
    ]

    operations = [
        migrations.RunPython(update_dates),
    ]
