# Generated by Django 3.2.12 on 2022-07-02 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('season_year', models.CharField(max_length=20)),
            ],
        ),
    ]
