# Generated by Django 3.2.12 on 2022-07-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_status',
            field=models.CharField(blank=True, choices=[('Activate', 'Activate'), ('Deactivate', 'Deactivate')], max_length=100, null=True),
        ),
    ]
