# Generated by Django 3.2.12 on 2022-07-02 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('supplier', '0003_suppliercredit'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_ton', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_ton', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('advance_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('after_advance_payment', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_expense', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('frieght', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('bilty_details', models.CharField(blank=True, max_length=100, null=True)),
                ('bilty_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bilty_image', models.ImageField(blank=True, null=True, upload_to='bilty/img/')),
                ('purchase_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item', to='product.productcategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_supplier', to='supplier.supplier')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vehicle', to='vehicle.vehicle')),
            ],
        ),
    ]
