# Generated by Django 3.2.12 on 2022-07-02 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplierledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True)),
                ('credit_details', models.CharField(blank=True, max_length=200, null=True)),
                ('credit_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('dated', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger', to='supplier.supplier')),
            ],
        ),
    ]
