# Generated by Django 3.2.12 on 2022-07-01 21:12

from django.db import migrations


def update_dates(apps, schema_editor):
    purchase_ledger = apps.get_model('purchase', 'Purchase')
    ledger_payment = apps.get_model('supplier', 'SupplierCredit')

    for i in purchase_ledger.objects.all():
        i.dated = i.purchase_date
        i.save()

    for p in ledger_payment.objects.all():
        p.dated = p.credit_date
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_suppliercredit'),
    ]

    operations = [
        migrations.RunPython(update_dates),
    ]
