# Generated by Django 3.2.12 on 2022-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='bilty_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
